#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const configPath = path.join(rootDir, "js", "config.js");
const examplePath = path.join(rootDir, "js", "config.example.js");

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;
const youtubeApiKey = process.env.YOUTUBE_API_KEY;

if (supabaseUrl && supabaseAnonKey && youtubeApiKey) {
  const content = `// Auto-generated by scripts/generate-config.js
export const SUPABASE_URL = ${JSON.stringify(supabaseUrl)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(supabaseAnonKey)};
// Google Cloud Console에서 YouTube Data API v3 키 발급 후 채워 넣을 것.
// HTTP 리퍼러를 sugardjmusic.kr 로 제한해야 한다.
export const YOUTUBE_API_KEY = ${JSON.stringify(youtubeApiKey)};
`;
  fs.writeFileSync(configPath, content, "utf8");
  console.log("Successfully generated js/config.js from environment variables.");
} else if (fs.existsSync(configPath)) {
  console.log("js/config.js already exists. Keeping existing file.");
} else if (fs.existsSync(examplePath)) {
  fs.copyFileSync(examplePath, configPath);
  console.warn("WARNING: Created js/config.js from js/config.example.js with placeholder values.");
  console.warn("Please update js/config.js or set SUPABASE_URL, SUPABASE_ANON_KEY, YOUTUBE_API_KEY environment variables.");
} else {
  console.error("ERROR: Neither environment variables nor js/config.example.js found.");
  process.exit(1);
}
